### ISSUE TITLE
About the version of scipy

### ISSUE THREAD

**Issue by Lnan1615** [paulmtree/Lung-Segmentation-Project#2]
I have tried many versions of 'scipy', but none of them can work. 
"AttributeError: module 'scipy' has no attribute 'ndimage' ",it said. 
So what is the right version of 'scipy'?

**Comment by paulmtree** [comment]
Have you tried this method? https://stackoverflow.com/questions/8200348/ndimage-missing-from-scipy

If that does not work, try this https://github.com/PolymerGuy/muDIC/issues/12. They say to use version 1.2.1 or try ndimage.imread to imageio.imread.

**Comment by paulmtree** [comment]
No response in a while, assuming this is closed.
